# Stuff
PointDisplay:
  Prefix: ""
  Suffix: " &8(&7%lp%&8/&e%max-lp%&8)"
  FullColor: '&9'
  EmptyColor: '&7'
  PreviewText: "&3&lLevelPoints &8(&7%lp%&8)"
  
DataDisplay:
  BlocksBroken: "&aBlocks Broken&8: &7%blocks%"
  EntityKills: "&aKills&8: &7%kills%"
  DamageAbsorbed: "&aDamage Negated&8: &7%damage-abs%"
  ItemUses: "&aTimes Used&8: &7%times-used%"
  ToolGrade: "&aGrade&8: &7%tool-grade%"
  ToolLevel: "&aLevel&8: &7%level%"

  Status:
    Unclaimed: "&7this tool is unclaimed, left-click to claim"
    Claimed: "&8left-click to manage item"
    Editing: "&eyou are currently editing this tool"
    Preview: "&eclick to apply upgrades"
  
    
EditorUI:
  MainTitle: "&2&lEditor&7: &8&l"
  
  Main:
    ModifyName: "&e&lChange Name"
    ModifyOwner: "&c&lModify Owner"
    ModifyEnchants: "&d&lMange Enchants"
    UpgradeItem: "&a&lUpgrade to next Tier" 
     
Stats:
  Item:
    Attack:
      Display: "&9Attack Damage"
      ScalePerLevel: 1.0
    Armor:
      Display: "&bArmor Strengh"
      ScalePerLevel: 1.0
    BonusHP:
      Display: "&cBonus Health points"
      ScalePerLevel: 0.1
    MovementSpeed:
      Display: "&bMovement Speed"
      ScalePerLevel: 0.1
    
      
      
      
    
